import warnings
warnings.filterwarnings("ignore")

import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st
import shap

st.set_page_config(
    page_title="RavenStack Account Health",
    page_icon="📊",
    layout="wide"
)

MODEL_FILE = "ravenstack_final_random_forest_model.joblib"
DATA_FILE = "ravenstack_pm_accounts.csv"

FEATURES = [
    "account_age_days",
    "subscription_tenure_days",
    "days_since_latest_subscription_start"
]

@st.cache_resource
def load_model():
    return joblib.load(MODEL_FILE)

@st.cache_data
def load_data():
    return pd.read_csv(DATA_FILE)

try:
    model = load_model()
    accounts = load_data()
except FileNotFoundError as e:
    st.error(
        f"Missing file: {e.filename}. "
        "Upload the model and account CSV generated by the export cell."
    )
    st.stop()

missing = [c for c in FEATURES if c not in accounts.columns]
if missing:
    st.error("Missing final model features: " + ", ".join(missing))
    st.stop()

X = accounts[FEATURES].copy()

@st.cache_data
def score(_model, data):
    return _model.predict_proba(data)[:, 1]

accounts["churn_probability"] = score(model, X)
accounts["health_score"] = 1 - accounts["churn_probability"]

def risk_group(p):
    if p >= 0.50:
        return "High Risk"
    if p >= 0.30:
        return "Medium Risk"
    return "Lower Risk"

accounts["risk_category"] = accounts["churn_probability"].apply(risk_group)

# Prepare SHAP using the same preprocessing stored inside the frozen pipeline.
if hasattr(model, "named_steps"):
    rf = model.named_steps["model"]

    if "preprocessor" in model.named_steps:
        preprocessor = model.named_steps["preprocessor"]
        X_shap = preprocessor.transform(X)
        try:
            shap_names = list(preprocessor.get_feature_names_out())
        except Exception:
            shap_names = FEATURES
    else:
        X_shap = X
        shap_names = FEATURES
else:
    rf = model
    X_shap = X
    shap_names = FEATURES

explainer = shap.TreeExplainer(rf)

def get_shap_values(position):
    values = explainer.shap_values(X_shap[position:position + 1])

    if isinstance(values, list):
        values = values[1]
    elif np.ndim(values) == 3:
        values = values[:, :, 1]

    return np.asarray(values).reshape(-1)

def label(name):
    name = name.replace("numeric__", "")
    return {
        "account_age_days": "Account age",
        "subscription_tenure_days": "Subscription tenure",
        "days_since_latest_subscription_start":
            "Days since latest subscription start"
    }.get(name, name)

def action_for(feature, positive):
    feature = feature.replace("numeric__", "")

    if not positive:
        return "Continue normal monitoring."

    actions = {
        "account_age_days":
            "Review engagement and consider a proactive customer-success check-in.",
        "subscription_tenure_days":
            "Review adoption and customer value during the subscription lifecycle.",
        "days_since_latest_subscription_start":
            "Review recent subscription activity and renewal status."
    }

    return actions.get(
        feature,
        "Review the account context and consider proactive outreach."
    )

st.sidebar.title("RavenStack")
st.sidebar.caption("Account-level churn risk and health scoring")

risk_filter = st.sidebar.multiselect(
    "Risk categories",
    ["High Risk", "Medium Risk", "Lower Risk"],
    default=["High Risk", "Medium Risk", "Lower Risk"]
)

top_k = st.sidebar.slider(
    "Accounts to display",
    5,
    min(50, len(accounts)),
    min(10, len(accounts)),
    5
)

st.title("RavenStack Account Health Dashboard")
st.caption("Proactive B2B SaaS customer churn risk prioritisation")

high = int((accounts["risk_category"] == "High Risk").sum())
medium = int((accounts["risk_category"] == "Medium Risk").sum())

c1, c2, c3, c4 = st.columns(4)
c1.metric("Accounts scored", f"{len(accounts):,}")
c2.metric("High-risk accounts", high)
c3.metric("Medium-risk accounts", medium)
c4.metric(
    "Average churn probability",
    f"{accounts['churn_probability'].mean():.1%}"
)

overview, priority, lookup, methodology = st.tabs([
    "Portfolio Overview",
    "Risk Prioritisation",
    "Account Lookup",
    "Model & Methodology"
])

with overview:
    st.subheader("Risk distribution")

    counts = accounts["risk_category"].value_counts().reindex(
        ["High Risk", "Medium Risk", "Lower Risk"],
        fill_value=0
    )

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(counts.index, counts.values)
    ax.set_ylabel("Accounts")
    ax.set_title("Accounts by risk category")
    plt.xticks(rotation=15)
    st.pyplot(fig)
    plt.close(fig)

    st.subheader("Highest-risk accounts")

    cols = [c for c in [
        "account_id", "account_name", "current_plan_tier",
        "total_mrr", "churn_probability", "health_score",
        "risk_category"
    ] if c in accounts.columns]

    table = accounts.sort_values(
        "churn_probability", ascending=False
    )[cols].head(top_k).copy()

    table["churn_probability"] = table["churn_probability"].map(
        lambda x: f"{x:.1%}"
    )
    table["health_score"] = table["health_score"].map(
        lambda x: f"{x:.1%}"
    )

    st.dataframe(table, use_container_width=True, hide_index=True)

with priority:
    st.subheader("Customer-success prioritisation")

    filtered = accounts[
        accounts["risk_category"].isin(risk_filter)
    ].sort_values("churn_probability", ascending=False)

    cols = [c for c in [
        "account_id", "account_name", "churn_probability",
        "health_score", "risk_category", "current_plan_tier", "total_mrr"
    ] if c in filtered.columns]

    st.dataframe(
        filtered[cols].head(top_k),
        use_container_width=True,
        hide_index=True
    )

    st.subheader("Top-K capture")

    if "target_future_churn" in accounts.columns:
        total = int(accounts["target_future_churn"].sum())

        for k in [5, 10, 20, 30]:
            if k <= len(accounts) and total > 0:
                captured = int(
                    accounts.sort_values(
                        "churn_probability", ascending=False
                    ).head(k)["target_future_churn"].sum()
                )

                st.write(
                    f"Top {k}: {captured}/{total} future-churn accounts "
                    f"captured ({captured / total:.1%})"
                )
    else:
        st.write(
            "Rank accounts by predicted churn probability for prioritisation."
        )

with lookup:
    st.subheader("Account lookup")

    selected = st.selectbox(
        "Select account",
        accounts["account_id"].astype(str).tolist()
    )

    pos = accounts.index[
        accounts["account_id"].astype(str) == selected
    ][0]

    row = accounts.loc[pos]

    a, b, c = st.columns(3)

    a.metric(
        "Churn probability",
        f"{row['churn_probability']:.1%}"
    )

    b.metric(
        "Health score",
        f"{row['health_score']:.1%}"
    )

    c.metric(
        "Risk",
        row["risk_category"]
    )

    if "account_name" in row.index:
        st.write(f"**Account:** {row['account_name']}")

    if "current_plan_tier" in row.index:
        st.write(f"**Plan:** {row['current_plan_tier']}")

    if "total_mrr" in row.index:
        st.write(f"**MRR:** ${row['total_mrr']:,.0f}")

    st.divider()
    st.subheader("Why is this account receiving this score?")

    position = accounts.index.get_loc(pos)
    shap_values = get_shap_values(position)

    explanation = pd.DataFrame({
        "feature": [label(x) for x in shap_names],
        "shap": shap_values
    }).sort_values("shap")

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.barh(explanation["feature"], explanation["shap"])
    ax.axvline(0, linewidth=0.8)
    ax.set_xlabel("SHAP contribution to churn risk")
    ax.set_title("Account-level SHAP explanation")
    st.pyplot(fig)
    plt.close(fig)

    st.caption(
        "Positive SHAP values increase the model's predicted churn risk; "
        "negative values reduce it. SHAP explains the model prediction "
        "and does not prove causality."
    )

    strongest = explanation.iloc[
        explanation["shap"].abs().argmax()
    ]

    st.subheader("Recommended PM action")

    if row["churn_probability"] >= 0.50:
        st.warning(
            "Prioritise this account for proactive customer-success review."
        )
    elif row["churn_probability"] >= 0.30:
        st.info(
            "Consider a proactive check-in and continue monitoring."
        )
    else:
        st.success(
            "No immediate intervention is indicated by the model."
        )

    st.write(
        "**Suggested action:** "
        + action_for(
            strongest["feature"],
            strongest["shap"] > 0
        )
    )

    st.write(
        "**Note:** Recommendations are decision-support suggestions "
        "based on model signals. They should be reviewed alongside "
        "customer context before action is taken."
    )

with methodology:
    st.subheader("Final dissertation model")

    st.markdown("""
**Model:** Random Forest

**Final features**
- account_age_days
- subscription_tenure_days
- days_since_latest_subscription_start

**Training population:** 332 accounts

**Test population:** 83 accounts

**Training CV ROC-AUC:** 0.6654 ± 0.0613

**Final test ROC-AUC:** 0.6148

**Final test PR-AUC:** 0.5085

**Prediction horizon:** 90 days
""")

    st.info(
        "The application loads the frozen model. It does not retrain, "
        "use SMOTE, use XGBoost, or tune against the test set."
    )

    st.write(
        "The health score is 1 minus predicted churn probability. "
        "SHAP explains which features contributed to each prediction; "
        "these explanations are not causal claims."
    )
